[home]
account = "0x7ae09e9963c835959b06240ba69b00febdff681a"
ipc = "./examples/parity_POA_simple/jsonrpc.ipc"
required_confirmations = 0
request_timeout = 360

[home.contract]
bin = "contracts/EthereumBridge.bin"

[foreign]
account = "0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
ipc = "./examples/parity_kov/jsonrpc.ipc"
required_confirmations = 0
request_timeout = 360

[foreign.contract]
bin = "contracts/KovanBridge.bin"

[authorities]
accounts = [
	"0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
]
required_signatures = 1

[transactions]
home_deploy = { gas = 3000000, gas_price = 21000000000 }
foreign_deploy = { gas = 3000000, gas_price = 21000000000 }
deposit_relay = { gas = 100000 }