[mainnet]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
ipc = "/Users/marek/Library/Application Support/io.parity.ethereum/jsonrpc.ipc"
deploy_tx = { gas = 600000 }
required_confirmations = 0

[mainnet.contract]
bin = "contracts/EthereumBridge.bin"
abi = "contracts/EthereumBridge.abi"

[testnet]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
ipc = "/Users/marek/Library/Application Support/io.parity.ethereum/jsonrpc.ipc"
deploy_tx = { gas = 600000 }
required_confirmations = 0

[testnet.contract]
bin = "contracts/KovanBridge.bin"
abi = "contracts/KovanBridge.abi"
