[mainnet]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
ipc = "/Users/marek/Library/Application Support/io.parity.ethereum/jsonrpc.ipc"
required_confirmations = 0

[mainnet.transactions]
deploy = { gas = 600000 }

[mainnet.contract]
bin = "contracts/EthereumBridge.bin"
abi = "contracts/EthereumBridge.abi"

[testnet]
account = "0x006e27b6a72e1f34c626762f3c4761547aff1421"
ipc = "/Users/marek/Library/Application Support/io.parity.ethereum/jsonrpc.ipc"
required_confirmations = 0

[testnet.transactions]
deploy = { gas = 600000 }

[testnet.contract]
bin = "contracts/KovanBridge.bin"
abi = "contracts/KovanBridge.abi"

[authorities]
accounts = [
	"0x006e27b6a72e1f34c626762f3c4761547aff1421",
	"0x006e27b6a72e1f34c626762f3c4761547aff1421",
	"0x006e27b6a72e1f34c626762f3c4761547aff1421"
]
required_signatures = 2
