[mainnet]
account = "0x7058681adfb80341ddf3b009e3f55fee6b6e226e"
ipc = "./examples/parity_ora/jsonrpc.ipc"
required_confirmations = 0

[mainnet.contract]
bin = "contracts/EthereumBridge.bin"

[testnet]
account = "0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
ipc = "./examples/parity_kov/jsonrpc.ipc"
required_confirmations = 0

[testnet.contract]
bin = "contracts/KovanBridge.bin"

[authorities]
accounts = [
	"0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
]
required_signatures = 1

[transactions]
mainnet_deploy = { gas = 1000000 }
testnet_deploy = { gas = 3000000 }
deposit_relay = { gas = 100000 }