[parity]
chain = "examples/parity_spec_oracles.json"
base_path = "./examples/parity_ora"

[account]
unlock = ["0x7058681adfb80341ddf3b009e3f55fee6b6e226e"]
password = ["examples/parity_password_oracles"]

[mining]
engine_signer = "0x7058681adfb80341ddf3b009e3f55fee6b6e226e"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
