[parity]
chain = "examples/parity_spec_POA_private.json"
base_path = "./examples/parity_POA"

[account]
unlock = ["0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"]
password = ["examples/parity_password_POA_private"]

[network]
port = 30333

[websockets]
port = 8556

[rpc]
cors = "null"
interface = "all"
hosts = ["all"]
port = 8555
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[mining]
engine_signer = "0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0

[misc]
#logging="poa=trace,signer=trace,engine=trace,own_tx=trace,txqueue=trace,sync=trace"
logging="poa=trace,signer=trace,engine=trace,own_tx=trace,txqueue=trace"