[parity]
chain = "kovan"
base_path = "./examples/parity_kov"

[account]
unlock = ["0x005364854d51A0A12cb3cb9A402ef8b30702a565"]
password = ["examples/parity_password_kovan"]

[network]
port = 30333

[rpc]
port = 8555

[websockets]
port = 8556

[mining]
engine_signer = "0x005364854d51A0A12cb3cb9A402ef8b30702a565"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
