[parity]
chain = "examples/parity_spec_POA_2_private_simple.json"
base_path = "./examples/parity_POA_2_simple"

[account]
unlock = ["0x00dB9af45C6f241432F2cBE412c6969cB7778d98"]
password = ["examples/parity_password_kovan"]

[network]
port = 30333

[websockets]
port = 8556

[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8555
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[mining]
engine_signer = "0x00dB9af45C6f241432F2cBE412c6969cB7778d98"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0