[parity]
chain = "examples/parity_spec_oracles.json"
base_path = "./examples/parity_ora"

[account]
unlock = ["0x00a6F6A140a3E2991c555dCCb36B4FBa7A46b0D8"]
password = ["examples/parity_password_oracles"]

[mining]
engine_signer = "0x00a6F6A140a3E2991c555dCCb36B4FBa7A46b0D8"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
