[parity]
chain = "examples/parity_spec_oracles.json"
base_path = "./examples/parity_ora"

[account]
unlock = ["0xDd0BB0e2a1594240fED0c2f2c17C1E9AB4F87126"]
password = ["examples/parity_password_oracles"]

[mining]
engine_signer = "0xDd0BB0e2a1594240fED0c2f2c17C1E9AB4F87126"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
