[parity]
chain = "kovan"
base_path = "./examples/parity_kov"

[account]
unlock = ["0xe83fdc372e6c5c0bc1500b42282c035b994d8b78"]
password = ["examples/parity_password_kovan"]

[network]
port = 30333

[rpc]
port = 8555

[websockets]
port = 8556

[mining]
engine_signer = "0xe83fdc372e6c5c0bc1500b42282c035b994d8b78"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0
