[parity]
chain = "examples/parity_spec_POA_private_simple.json"
base_path = "./examples/parity_POA_simple"

[account]
unlock = ["0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"]
password = ["examples/parity_password_oracles_private"]

[mining]
engine_signer = "0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0