# AlphaTestTestNet branch
[parity]
chain = "examples/parity_spec_oracles.json"
base_path = "./examples/parity_ora"
[network]
nat="extip:195.178.109.65"
bootnodes=["enode://886bc3f5f6f6258a89febdf31c71514e27b3647151e96e16bd4bdf6328884b3e8d41bcfb64095496e3701142c4b1f0e6047781d353674b61a45b023845ea742a@40.117.197.50:30300"]
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
interface = "0.0.0.0"
port = 8180
[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]
[dapps]
cors = "all"
interface = "0.0.0.0"
hosts = ["all"]
port = 8080
[account]
unlock = ["0x00a6F6A140a3E2991c555dCCb36B4FBa7A46b0D8"]
password = ["examples/parity_password_oracles_private"]