[parity]
chain = "examples/parity_spec_oracles_private.json"
base_path = "./examples/parity_ora"

[account]
unlock = ["0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"]
password = ["examples/parity_password_oracles_private"]

[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[mining]
engine_signer = "0xeaeba7869e23a328a0a92620bba1a7a6aaed26cb"
reseal_on_txs = "all"
usd_per_tx = "0"
reseal_min_period = 0